### ISSUE TITLE
The 'DaprPackage' package did not load correctly

### ISSUE THREAD

**Issue by tomasKosar** [microsoft/vs-dapr#4] opened 2023-10-24 16:38 UTC
I just want to say that I am excited to start using this extension and I appreciate the hard work on this.

Unfortunately the new Dapr extension is not working for me. It does not work in my existing project with Dapr as well as in new Web API project created from VS template.

I am getting this error message when I try to use the extension.
![Screenshot 2023-10-24 172152](https://github.com/microsoft/vs-dapr/assets/34095203/f9482f18-0723-473d-98d4-5c1ab26c22dc)

In the suggested ActivityLog.xml there I see this error:

SetSite failed for package [DaprPackage]Source: &apos;Dapr.VisualStudio.Package&apos; Description: Could not load type &apos;System.Reactive.Linq.DispatcherObservable&apos; from assembly &apos;System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263&apos;.&#x000D;&#x000A;System.TypeLoadException: Could not load type &apos;System.Reactive.Linq.DispatcherObservable&apos; from assembly &apos;System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263&apos;.&#x000D;&#x000A;   at Dapr.VisualStudio.PackageComponents.DaprRunMonitor.&lt;InitializeAsync&gt;d__6.MoveNext()&#x000D;&#x000A;   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)&#x000D;&#x000A;   at Dapr.VisualStudio.PackageComponents.DaprRunMonitor.InitializeAsync(DaprPackage package, CancellationToken cancellationToken)&#x000D;&#x000A;   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()&#x000D;&#x000A;   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)&#x000D;&#x000A;   at Dapr.VisualStudio.DaprPackage.&lt;InitializePackageComponentsAsync&gt;d__18.MoveNext() in D:\a\1\s\src\Dapr.VisualStudio.Package\DaprPackage.cs:line 108&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Dapr.VisualStudio.DaprPackage.&lt;InitializeAsync&gt;d__14.MoveNext() in D:\a\1\s\src\Dapr.VisualStudio.Package\DaprPackage.cs:line 76&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)

Based on mention of "System.Reactive, Version=6.0.0.0" then I tried to create new .NET 6 project rather then .NET 7. Now I am not getting any error. But "Dapr" project does not appear in the solution so I am unable to set startup project and run the solution in dapr.

Any help on how to make this work would be appreciated. Thanks.

**Comment by philliphoff** [comment] 2023-10-24 20:40
@tomasKosar Apologies for hitting this issue!  You're not the only one (though I've yet to reproduce it myself).  That said, I believe I understand what the issue is (a conflict between versions of System.Reactive.dll shipped with Visual Studio 17.7) even if I'm not sure yet what an appropriate fix would be.

I suggest you try Visual Studio 17.8 (currently in [preview](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview)) and let me know if that allows you to move forward.  This should install side-by-side an existing Visual Studio installation.

**Comment by philliphoff** [comment] 2023-10-24 21:18
It looks like I can't multi-target 17.7 and 17.8 (as the extensibility SDK has breaking changes), so I have little choice but to move to 17.8 despite still being in preview itself.

**Comment by tomasKosar** [comment] 2023-10-25 11:51
OK Thanks for the explanation.

I have VS preview next to VS as well and I regularly switch between them. I did not have time to try VS preview yesterday. I tried it today and it seems like it works alright. So I will be using VS preview until this extension will be available in standard VS version. Thanks.

**Comment by philliphoff** [comment] 2023-10-25 15:48
Glad you're now up and running.  Closing as fixed as of v0.1.1024.3.

**Closed by philliphoff** 2023-10-25 15:47 UTC
Labels: bug, P0
