### ISSUE TITLE
Can't find extension on VS

### ISSUE THREAD

**Issue by andrevlins** [microsoft/vs-dapr#7] opened 2023-11-27 11:40 UTC
I'm following the instructions to install this preview extension but had no success, the extension don't show as you can see on these screenshots.

![image](https://github.com/microsoft/vs-dapr/assets/5325718/0ce4745f-1025-4341-b883-3261925b1fcc)

![image](https://github.com/microsoft/vs-dapr/assets/5325718/0091ea55-b7cc-474d-86b9-0931cbe38b34)

![image](https://github.com/microsoft/vs-dapr/assets/5325718/44b27751-59b8-484e-955e-967f941cda8f)

**Comment by philliphoff** [comment] 2023-11-29 06:05
@andrevlins Apologies, but it seems I've let the temporary links to the unofficial feed expire, which might be the cause of your issue.  I've generated new builds/links; please try again and let me know if you run into any other issues.

**Comment by andrevlins** [comment] 2023-11-29 11:28
Forgot to mention the visual studio version:

![image](https://github.com/microsoft/vs-dapr/assets/5325718/474049c3-dd2e-4a4d-94f7-56c94e3a25f6)

**Comment by andrevlins** [comment] 2023-11-29 18:47
Unfortunately I cannot use version 17.8 since I am following and trying to collaborate with the .net aspire project and it requires at least 17.9.

I'll try to get time to install 17.8 side by side just to test the extension installation.

**Comment by philliphoff** [comment] 2023-11-30 00:16
I use 17.8 and 17.9 side-by-side for working with Aspire as well.  While perhaps not super convenient, I found the two versions of VS do work well together.  Since there are breaking manifest/APIs changes between 17.8 and 17.9, I don't know viability of supporting both; I'd need to investigate our options there.

**Comment by andrevlins** [comment] 2023-11-30 00:41
Thanks @philliphoff I'll try side-by-side

**Comment by philliphoff** [comment] 2023-12-04 21:17
@andrevlins FYI, I've built/published a new version of the extension that works around the Container Tools issue.

**Comment by philliphoff** [comment] 2023-12-15 07:26
Closing as resolved (with updated links and a workaround for the Container Tools issue).

**Closed by philliphoff** 2023-12-15 07:26 UTC
